server:
  port: 8000
  grpc:
    port: 50052
spring:
  flyway:
    url: ${spring.datasource.url};DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:h2:mem:poc
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
